### ISSUE TITLE
Timesteps in aerosol auxinput15 file not read corretly by WRF

### ISSUE THREAD

**Issue by yoselita** [CORDEX-WRF-community/euro-cordex-cmip6#6]
The yearly aerosol files are created in a way to replicate the metadata and timestamps from wrflowinp file (following suggestion given [here](https://forum.mmm.ucar.edu/threads/aod550-wrf-solar-wrf-exe-is-shifting-the-auxinput15s-timestep-1-hour.12123/)). It looks like that WRF has an issue with reading these aerosol files. It does not read correctly the times provided in the aerosol file. For that reason, the aerosol file that will be read by WRF needs to start at the same time as the WRF run. So this means if, for example, you start your run on 01.09.2013, and you have your aerosol file from 01.01.2013, WRF does not look for the 01.09.2013,  but it starts to read the file from the initial date in the provided aerosol file (i.e. 01.01.2013), with the frequency given in the namelist.input (i.e. daily). For that reason it is necessary to set the aerosol files in a way to correspond to the start or restart of your simulation. This means that every time when restarting the simulation, the aerosol file need to start with the same restarting date.

**Comment by jesusff** [comment]
Warned in [README-checklist.md](https://github.com/CORDEX-WRF-community/euro-cordex-cmip6/blob/c902f5ac2/README-checklist.md) and script to fix it in [util/update_and_restart.py](https://github.com/CORDEX-WRF-community/euro-cordex-cmip6/blob/c902f5ac2/util/update_and_restart.py). Closing ...
